# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:34
from __future__ import unicode_literals

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=accounting.models.generate_uuid, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='AccountOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.CharField(default=accounting.models.generate_uuid, max_length=128, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.AddField(
            model_name='accountoperations',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation'),
        ),
        migrations.AddField(
            model_name='account',
            name='operations',
            field=models.ManyToManyField(through='accounting.AccountOperations', to='accounting.Operation'),
        ),
    ]
